
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import { Poppins } from "next/font/google";
import NextAuthProvider from "@/provider/NextAuthProvider";
const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
})
export const myBanglaFont = localFont(
  {
    src: '../fonts/mayaboti-Italic.ttf'
  }
)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Hero Kidz",

    template: "%s | Hero Kidz"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (


    <NextAuthProvider>
      <html
        lang="en"
        className={`${poppins.className} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">

          <header className="py-2 md:w-11/12 mx-auto">
            <Navbar>

            </Navbar>
          </header>

          <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100vh-302px)]">
            {children}
          </main>




          <footer>
            <Footer></Footer>
          </footer>
        </body>
      </html>

    </NextAuthProvider>





  );
}
